spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tacodb
    username: admin
    password: 1234
  jpa:
    hibernate:
      dll-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect