spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tacodb
    username: admin
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: admin
    oauth2:
      client:
        registration:
          facebook:
            clientId: <facebook client Id>
            clientSecret: <facebook client secret>
            scope: email, public_profile